dataset:
  path: ../data_hydra/sphinx_compatible_dense/square/ph/data
  camera_views: agentview_image
  image_size: 84
dp:
  shift_pad: 6
  cond_unet:
    kernel_size: 5
    use_prop: 1
  use_ddpm: 0
num_epoch: 20
epoch_len: 10000
num_eval: 10
use_ema: 1
ema_tau: 0.01
batch_size: 256
lr: 1e-4
weight_decay: 1e-6
cosine_schedule: 1
lr_warm_up_steps: 500
use_wb: 1
save_dir: exps/hydra/hydra_dense_data_recorder
is_sim: 1